config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root to: "items#index"
  resources :items do
    resources :purchase, only: [:show] do
      member do       # すべてのアクションに対してitem_idを渡す
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection do
      get 'search'
    end
  end



  resources :users do
    member do
      get "profile"
      get "personalinformation"
      get "tab1"
      get "tab2"
      get "tab3"
      get "logout"
      get "payment"
    end
  end
  
  resources :signup, only: [:index,:create] do
    collection do
      get 'step1'                               # 会員情報
      post 'step1', to: 'signup#post_step1'
      get 'step2'                               # 電話番号
      get 'step3'                               # 住所
      post 'step3', to: 'signup#post_step3'
      get 'step4'                               # クレジットカード
      get 'done'                                # 完了
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable,omniauth_providers: %i[facebook google_oauth2]

  has_many :credits
  has_one :profile, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  has_many :items

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: {minimum: 7}
  validates :nickname, presence: true, length: {maximum: 30}


  def self.without_sns_data(auth)
    user = User.find_by(email: auth.info.email)

    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        password: Devise.friendly_token.first(8)
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider,
      )
    end
    return { user: user, sns: sns}
  end

  def self.with_sns_data(auth, snscredential)

    user = User.find_by(id: snscredential.user_id)

    unless user.present?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        password: Devise.friendly_token.first(8)
      )
    end

    return { user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.find_by(uid: uid, provider: provider)
    
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user, sns: sns }
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
    @profile = Profile.new
    session[:password] = @user.password
  end

  def google_oauth2
    callback_for(:google)
    @profile = Profile.new
    session[:password] = @user.password
  end

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      session[:uid] = @sns.uid
      session[:provider] = @sns.provider
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :tab1,:tab2, :tab3,:logout]
  before_action :move_to_index

  


  def show
  end

  def tab1
  end

  def tab2
  end

  def tab3
  end
  
  def profile
  end

  def personalinformation
    @user = User.find(params[:id])
    @profiles = @user.profile
    
  end  

  def logout
  end  

  
  private
  def set_user
    @user = User.find(params[:id])
    @items = @user.items
    @sell_items = @items.where(buyer_id: nil)
    @bought_items = @items.where.not(buyer_id: nil)
  end
  
  def move_to_index
    @user = User.find(params[:id])
    redirect_to root_path unless user_signed_in? && current_user.id == @user.id
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage.html.haml
.mypage-content
  %section.mypage-content__user-icon
    = link_to '#' do
      %figure
        = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", size: '48x48'
      %h2.mypage-content__user-name
        = @user.nickname
      .mypage-content__status
        .mypage-content__reviews
          評価
          %span.mypage-content__reviews
            Bad
        .mypage-content__sell
          出品数
          %span.mypage-content__sell 
            = @items.count
              
  %section.mypage-content__main-tab-container
    %ul.mypage-content__tabs
      %li.mypage-content__tab.mypage-content__tab--active
        %h3
          = link_to '#', id: 'mypage-content__tab-notification' do
            お知らせ
      %li.mypage-content__tab
        %h3
          = link_to '#', id: 'mypage-content__tab-todo' do
            やることリスト
    .mypage-content__tab-content
      %ul.mypage-content__item-list.mypage-content__item-list--active{ id: 'mypage-content__item-list-notification' }
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag "logo_red.svg", size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                《メルペイはじめよう》
              %time
                = icon 'far', 'clock'
                %span
                  2 時間前
            = icon 'fas', 'chevron-right'
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag "logo_red.svg", size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                《メルペイはじめよう》
              %time
                = icon 'far', 'clock'
                %span
                  2 時間前
            = icon 'fas', 'chevron-right'
        %li.mypage-content__go-list
          = link_to '#' do
            一覧を見る
      %ul.mypage-content__item-list{ id: 'mypage-content__item-list-todo' }
        %li.mypage-content__item-not-found
          現在、やることリストはありません
  %section.mypage-content__secondary-tab-container
    %h2.mypage-content__tab-head
      購入した商品
    %ul.mypage-content__tabs
      %li.mypage-content__tab.mypage-content__tab--active
        %h3
          = link_to '#', id: 'mypage-content__tab-transaction-now' do
            取引中
      %li.mypage-content__tab
        %h3
          = link_to '#', id: 'mypage-content__tab-transaction-old' do
            過去の取引
    .mypage-content__tab-content
      %ul.mypage-content__item-list.mypage-content__item-list--active{ id: 'mypage-content__item-list-transaction-now' }
        %li.mypage-content__item-not-found
          取引中の商品がありません
      %ul.mypage-content__item-list{ id: 'mypage-content__item-list-transaction-old' }
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag '', size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                「iPhone充電ケーブル3本セット」 を購入しました。
                %span
                  取引が完了しました
              .mypage-content__item-status.mypage-content__item-status--done
                取引完了
            = icon 'fas', 'chevron-right'
          %li.mypage-content__go-list
            = link_to '#' do
              一覧を見る

app/views/users/_side-bar.html.haml
.mypage-side-bar
  %nav.mypage-side-bar__nav
    %ul.mypage-side-bar__list
      %li
        -# = link_to mypage_index_path, class: 'mypage-side-bar__list-item mypage-side-bar__list-item--active' do
        = link_to user_path(current_user), class: 'mypage-side-bar__list-item mypage-side-bar__list-item--active' do
          マイページ
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          お知らせ
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          やることリスト
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          いいね！一覧
          = icon 'fas', 'chevron-right'
      %li
        -# = link_to new_sell_path, class: 'mypage-side-bar__list-item' do
        = link_to new_item_path , class: 'mypage-side-bar__list-item' do
          出品する
          = icon 'fas', 'chevron-right'
      %li
        -# = link_to listing_listing_mypage_index_path, class: 'mypage-side-bar__list-item' do
        = link_to tab1_user_path , class: 'mypage-side-bar__list-item' do
          出品した商品 - 出品中
          = icon 'fas', 'chevron-right'
      %li
        -# = link_to  listing_in_progress_mypage_index_path, class: 'mypage-side-bar__list-item' do
        = link_to tab2_user_path, class: 'mypage-side-bar__list-item' do
          出品した商品 - 取引中
          = icon 'fas', 'chevron-right'
      %li
        -# = link_to  listing_completed_mypage_index_path, class: 'mypage-side-bar__list-item' do
        = link_to tab3_user_path, class: 'mypage-side-bar__list-item' do
          出品した商品 - 売却済み
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          購入した商品 - 取引中
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          購入した商品 - 過去の取引
          = icon 'fas', 'chevron-right'
      %li
        = link_to "https://news.yahoo.co.jp/", class: 'mypage-side-bar__list-item' do
          ニュース一覧
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          評価一覧
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          ガイド
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          お問い合わせ
          = icon 'fas', 'chevron-right'
    %h3.mypage-side-bar__nav-head
      メルペイ
    %ul.mypage-side-bar__list
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          残高・振込申請
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          ポイント
          = icon 'fas', 'chevron-right'
    %h3.mypage-side-bar__nav-head
      設定
    %ul.mypage-side-bar__list
      %li
        -# = link_to profile_mypage_index_path, class: 'mypage-side-bar__list-item' do
        = link_to profile_user_path(current_user.id), class: 'mypage-side-bar__list-item' do
          プロフィール
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          発送元・お届け先住所変更
          = icon 'fas', 'chevron-right'
      %li
        -# = link_to new_card_path, class: 'mypage-side-bar__list-item' do
        = link_to payment_user_path(current_user.id), class: 'mypage-side-bar__list-item' do
          支払い方法
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          メール/パスワード
          = icon 'fas', 'chevron-right'
      %li
        -# = link_to identification_mypage_index_path, class: 'mypage-side-bar__list-item' do
        = link_to personalinformation_user_path(current_user.id), class: 'mypage-side-bar__list-item' do
          本人情報
          = icon 'fas', 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          電話番号の確認
          = icon 'fas', 'chevron-right'
      %li
        -# = link_to logout_mypage_index_path, class: 'mypage-side-bar__list-item' do
        = link_to logout_user_path(current_user), class: 'mypage-side-bar__list-item' do
          ログアウト
          = icon 'fas', 'chevron-right'

app/views/users/index.html.haml
= render "items/header"

.mypage-main-containe
  %main.mypage-container.clearfix
    = render 'users/mypage'
    = render 'users/side-bar'

= render "items/footer"

app/views/users/logout.html.haml
= render "items/header"
- breadcrumb :"/users/index/logout"
= render "layouts/breadcrumbs"

.mypage-main-containe
  %main.mypage-container.clearfix
  
    = render 'users/side-bar'

    .l-content
      .l-chapter-container
        %button.btn-default.btn-red1
          = link_to destroy_user_session_path, method: :delete,class:"logoutabe" do
            ログアウト
= render "items/footer"

app/views/users/payment.html.haml
= render "items/header"
- breadcrumb :"/users/index/payment"
= render "layouts/breadcrumbs"

.mypage-main-containe
  %main.mypage-container.clearfix
    = render 'users/side-bar'

    .l-content
      %section.l-container
        %h2.l-header 支払い方法
        .l-main
          .l-main__container
            %h3.l-main__header クレジットカード一覧
            .l-main__cont
              %button.submit_btn{type: "submit"}
                %i.far.fa-credit-card>
                クレジットカードを追加する
        .l-footer
          %p.info 支払い方法について &gt;


= render "items/footer"     

app/views/users/personalinformation.html.haml
= render "items/header"
- breadcrumb :"/users/index/personalinformation"
= render "layouts/breadcrumbs"
.mypage-main-containe
  %main.mypage-container.clearfix
  
    = render 'users/side-bar'

    .information-container
      .content
        %section.information-chapter-container
          %h2.information-chapter-head 本人情報の登録
          %form.information-inner
            %div
              %p
                お客さまの本人情報をご登録ください。
                %br/
                登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
              %p.text-right
                = link_to "#" ,class:"text-right" ,target:"_blank" do
                  本人確認書類のアップロードについて
                  %i.fas.fa-angle-right
            .form-group
              %label お名前
              %p 
                
                -# 下記の記載で表示させる場合はコントローラーで定義が必要
                = @profiles.last_name
                = @profiles.first_name
                
                
                -# 上記と同じ意味
                -# = current_user.profile.last_name
                -# = current_user.profile.first_name
            .form-group
              %label お名前カナ
              %p
                = @profiles.last_name_kana
                = @profiles.first_name_kana
            .form-group
              %label{for:"birthday"} 生年月日
              %p 
                = "#{@profiles.birth_year}/"
                = "#{@profiles.birth_month}/"
                = @profiles.birth_day
            .form-group
              %label{for:"zip_code"} 郵便番号
              %span.form-arbitrary 任意
              %input.input-default{name:"zip_code", placeholder:"例)1234567", type: "text", value: ""}/
            .form-group
              %label{for: "prefecture"} 都道府県
              %span.form-arbitrary 任意
              .select-wrap
                %i.material-icons arrow-down
                %select.select-default{name: "prefecture"}
                  %option --
                  %option 北海道
                  %option 青森県
                  %option 岩手県
                  %option 宮城県
                  %option 秋田県
                  %option 山形県
                  %option 福島県
                  %option 東京都
                  %option 神奈川県
                  %option 埼玉県
                  %option 千葉県
                  %option 茨城県
                  %option 栃木県
                  %option 群馬県
                  %option 山梨県
                  %option 新潟県
                  %option 長野県
                  %option 富山県
                  %option 石川県
                  %option 福井県
                  %option 愛知県
                  %option 岐阜県
                  %option 静岡県
                  %option 三重県
                  %option 大阪府
                  %option 兵庫県
                  %option 京都府
                  %option 滋賀県
                  %option 奈良県
                  %option 和歌山県
                  %option 鳥取県
                  %option 島根県
                  %option 岡山県
                  %option 広島県
                  %option 山口県
                  %option 徳島県
                  %option 香川県
                  %option 愛媛県
                  %option 高知県
                  %option 福岡県
                  %option 佐賀県
                  %option 長崎県
                  %option 熊本県
                  %option 大分県
                  %option 宮崎県
                  %option 鹿児島県
                  %option 沖縄県
            .form-group
              %label{for:"city"} 市区町村
              %span.form-arbitrary 任意
              %input.input-default{name:"city", placeholder: "横浜市緑区", type: "text", value: ""}/
            .form-group
              %label{for:"address1_label"} 番地
              %span.form-arbitrary 任意
              %input.input-default{name:"address1", placeholder:"例) 青山1-1-1", type:"text", value: ""}/
            .form-group
              %label{for:"address2_label"} 建物名
              %span.form-arbitrary 任意
              %input.input-default{name: "address2", placeholder: "例) 柳ビル103", type: "text", value: ""}/
            %button.btn-default.btn-red{:type => "submit"} 登録する
            .form-group.text-right
              %p
                = link_to "#" ,class:"text-right", target:"_blank" do
                  本人情報の登録について
                  %i.fas.fa-angle-right
            %input{name:"information-registration", type:"hidden"}/




= render "items/footer"    

app/views/users/profile.html.haml
= render "items/header"
- breadcrumb :"/users/index/profile"
= render "layouts/breadcrumbs"
.mypage-main-containe
  %main.mypage-container.clearfix
  
    = render 'users/side-bar'
  
    .l-content
      %section.l-container
        %h2.l-header プロフィール
        %form{:action => ""}
          .l-profile
            %i.fas.fa-user-circle.fa-3x
            %input.user-name{placeholder: "#{current_user.nickname}", type: "text"}/
          .setting-profile
            %textarea.user-description{placeholder: "例) こんにちは☆ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", :type => "textarea"}
            %button.submit_btn{type: "submit"} 変更する



= render "items/footer"          

app/views/users/show.html.haml
= render "items/header"
- breadcrumb :users
= render "layouts/breadcrumbs"

.mypage-main-containe
  %main.mypage-container.clearfix
    = render 'users/mypage'
    = render 'users/side-bar'

= render "items/footer"

app/views/users/tab1.html.haml
= render "items/header"
- breadcrumb :"/users/index/tab1"
= render "layouts/breadcrumbs"  
.mypage-main-containe
  %main.mypage-container.clearfix
    .l-content-tab
      %section.tab-container
        %h2.tab-header 出品した商品
        .tab-panel
          %ul.tab-group
            %li.tab.tab-A.is-active 出品中
            %li.tab.tab-B 取引中
            %li.tab.tab-C 売却済み
          .tab-content
            %ul.panel-group
              %li.panel.tab-A.is-show
                - if @sell_items.exists?
                  - @sell_items.each do |sell_item| 
                    .panel-container-c
                      .image-text
                        = image_tag "#{sell_item.image}", class:"panel-image"
                        %p.panel-message-item-name
                          = sell_item.name
                      .next-page
                        = link_to edit_item_path(sell_item.id), class: "pager-next" do
                          %i.fas.fa-chevron-right
                - else
                  = image_tag "logo_gray.svg", class:"tab-logo"
                  %h5.panel-content
                    出品中の商品がありません
              %li.panel.tab-B 
                = image_tag "logo_gray.svg", class:"tab-logo"
                %h5.panel-content
                  取引中の商品がありません
              %li.panel.tab-C 
                - if @bought_items.exists?
                  - @bought_items.each do |bought_item|
                    .panel-container-c
                      .image-text
                        = image_tag "#{bought_item.image}", class:"panel-image"
                        %p.panel-message-item-name
                          = bought_item.name
                - else 
                  = image_tag "logo_gray.svg", class:"tab-logo"
                  %h5.panel-content
                    売却済の商品がありません
      %ul.pager
        %li.pagers
          = link_to "#", class: "pager-prev" do
            %i.fas.fa-chevron-left
        %li.pagers
          = link_to "#", class: "pager-next" do
            %i.fas.fa-chevron-right
  


    = render 'users/side-bar'
= render "items/footer"

app/views/users/tab2.html.haml
= render "items/header"
- breadcrumb :"/users/index/tab2"
= render "layouts/breadcrumbs" 
  
.mypage-main-containe
  %main.mypage-container.clearfix
    .l-content-tab
      %section.tab-container
        %h2.tab-header 出品した商品
        .tab-panel
          %ul.tab-group
            %li.tab.tab-A 出品中
            %li.tab.tab-B.is-active 取引中
            %li.tab.tab-C 売却済み
          .tab-content
            %ul.panel-group
              %li.panel.tab-A
                - if @sell_items.exists?
                  - @sell_items.each do |sell_item| 
                    .panel-container-c
                      .image-text
                        = image_tag "#{sell_item.image}", class:"panel-image"
                        %p.panel-message-item-name
                          = sell_item.name
                      .next-page
                        = link_to edit_item_path(sell_item.id), class: "pager-next" do
                          %i.fas.fa-chevron-right
                - else
                  = image_tag "logo_gray.svg", class:"tab-logo"
                  %h5.panel-content
                    出品中の商品がありません
              %li.panel.tab-B.is-show
                = image_tag "logo_gray.svg", class:"tab-logo"
                %h5.panel-content
                  取引中の商品がありません
              %li.panel.tab-C 
                - if @bought_items.exists?
                  - @bought_items.each do |bought_item|
                    .panel-container-c
                      .image-text
                        = image_tag "#{bought_item.image}", class:"panel-image"
                        %p.panel-message-item-name
                          = bought_item.name
                - else 
                  = image_tag "logo_gray.svg", class:"tab-logo"
                  %h5.panel-content
                    売却済の商品がありません
      %ul.pager
        %li.pagers
          = link_to "#", class: "pager-prev" do
            %i.fas.fa-chevron-left
        %li.pagers
          = link_to "#", class: "pager-next" do
            %i.fas.fa-chevron-right
  


    = render 'users/side-bar'
= render "items/footer"

app/views/users/tab3.html.haml
= render "items/header"
- breadcrumb :"/users/index/tab3"
= render "layouts/breadcrumbs" 
  
.mypage-main-containe
  %main.mypage-container.clearfix
    .l-content-tab
      %section.tab-container
        %h2.tab-header 出品した商品
        .tab-panel
          %ul.tab-group
            %li.tab.tab-A 出品中
            %li.tab.tab-B 取引中
            %li.tab.tab-C.is-active 売却済み
          .tab-content
            %ul.panel-group
              %li.panel.tab-A
                - if @sell_items.exists?
                  - @sell_items.each do |sell_item| 
                    .panel-container-c
                      .image-text
                        = image_tag "#{sell_item.image}", class:"panel-image"
                        %p.panel-message-item-name
                          = sell_item.name
                      .next-page
                        = link_to edit_item_path(sell_item.id), class: "pager-next" do
                          %i.fas.fa-chevron-right
                - else
                  = image_tag "logo_gray.svg", class:"tab-logo"
                  %h5.panel-content
                    出品中の商品がありません
              %li.panel.tab-B 
                = image_tag "logo_gray.svg", class:"tab-logo"
                %h5.panel-content
                  取引中の商品がありません
              %li.panel.tab-C.is-show
                - if @bought_items.exists?
                  - @bought_items.each do |bought_item|
                    .panel-container-c
                      .image-text
                        = image_tag "#{bought_item.image}", class:"panel-image"
                        %p.panel-message-item-name
                          = bought_item.name
                - else 
                  = image_tag "logo_gray.svg", class:"tab-logo"
                  %h5.panel-content
                    売却済の商品がありません
      %ul.pager
        %li.pagers
          = link_to "#", class: "pager-prev" do
            %i.fas.fa-chevron-left
        %li.pagers
          = link_to "#", class: "pager-next" do
            %i.fas.fa-chevron-right
  


    = render 'users/side-bar'
= render "items/footer"