config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root to: "items#index"
  resources :items do
    resources :purchase, only: [:show] do
      member do       # すべてのアクションに対してitem_idを渡す
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection do
      get 'search'
    end
  end



  resources :users do
    member do
      get "profile"
      get "personalinformation"
      get "tab1"
      get "tab2"
      get "tab3"
      get "logout"
      get "payment"
    end
  end
  
  resources :signup, only: [:index,:create] do
    collection do
      get 'step1'                               # 会員情報
      post 'step1', to: 'signup#post_step1'
      get 'step2'                               # 電話番号
      get 'step3'                               # 住所
      post 'step3', to: 'signup#post_step3'
      get 'step4'                               # クレジットカード
      get 'done'                                # 完了
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord

  validates :user_id,:status,:derivery_fee,:price,:derivery_estimated,:description,:image,:category1,:category2,:category3,:prefecture_id, presence: true
  
  validates :name, presence: true, length: {maximum: 40}
  

  mount_uploader :image, ImageUploader
  belongs_to :user


  def self.search(search)
    if search
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :destroy, :update]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @items = Item.where(buyer_id: nil).includes(:user)
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: "出品完了やで！！！"
    else 
      render :new, alert: '出品できませんでした'
    end
  end


  def destroy
    if @item.user_id == current_user.id
      if @item.destroy
        redirect_to root_path, notice: "削除しました" if user_signed_in? && current_user.id == @item.user_id 
      else
        render :new, alert: "削除できませんでした"
      end
    else
      redirect_to root_path
    end
  end  

  def edit
    unless current_user.id == @item.user_id
      redirect_to items_path
    end
  end  

  def update
    if @item.user_id == current_user.id
      if @item.update(item_params)
        redirect_to root_path, notice: "編集完了したで" if user_signed_in? && current_user.id == @item.user_id
      else  
        render :edit, alert: "編集できませんでした"
      end
    else
      redirect_to root_path
    end
  end

  def show
    @user = @item.user_id
    @items = Item.where(user_id: @user, buyer_id: nil)
  end


  def search
    @items = Item.search(params[:keyword]).where(buyer_id: nil)
  end


  private

  def item_params
    params.require(:item).permit(
      :name, :size, :status, :derivery_fee, :derivery_method,
      :price, :derivery_estimated, :description, :image, :category1, :category2, :category3, :brand, :prefecture_id, :buyer_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
%footer.footerbg
  - if user_signed_in?
    #Exhibit
      = link_to new_item_path do
        .red_circle
          .Exhibit 出品
          %div
            %i.fas.fa-camera.fa-4x 
  - else
    #Exhibit
      = link_to new_user_session_path, data: {confirm: "ログインして下さい"} do
        .red_circle
          .Exhibit 出品
          %div
            %i.fas.fa-camera.fa-4x 
  .AD
    %aside.adm
      %div
        .AD_message1 スマホでかんたんフリマアプリ
        .AD_message2 今すぐ無料ダウンロード！
        %div
          = image_tag "logo_red.svg", id: "freemarket",alt: "フリマアイコン"
          = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
            =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg", class:"apple", alt: ""
          = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" do
            =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg", class: "google", alt: ""
      %figure
        =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/download_app_pc-a4418175e8be071827ac88d073f40e4a.png", id:"smartphone", alt: ""
  .footer
    %nav.footer_navi
      .description
        %h2 メルカリについて
        %ul
          %li.description_list
            = link_to "#" do
              会社概要(運営会社)
          %li.description_list
            = link_to "#" do
              採用情報
          %li.description_list
            = link_to "#" do
              プレスリリース
          %li.description_list
            = link_to "#" do
              公式ブログ
          %li.description_list
            = link_to "#" do
              メルカリロゴ利用ガイドライン
          = link_to "#" do
            %i.fab.fa-twitter.fa-2x
          = link_to "#" do
            %i.fab.fa-facebook-square.fa-2x
      .description
        %h2 ヘルプ＆ガイド
        %ul
          %li.description_list
            = link_to "#" do
              メルカリガイド
          %li.description_list
            = link_to "#" do
              らくらくメルカリ便
          %li.description_list
            = link_to "#" do
              ゆうゆうメルカリ便
          %li.description_list
            = link_to "#" do
              大型メルカリ便
          %li.description_list
            = link_to "#" do
              車体取引ガイド
          %li.description_list
            = link_to "#" do
              メルカリあんしん・あんぜん宣言！
          %li.description_list
            = link_to "#" do
              偽ブランド品撲滅への取り組み
          %li.description_list
            = link_to "#" do
              メルカリボックス
      .description
        %h2 プライバシーと利用規約
        %div
          %ul
            %li.description_list
              = link_to "#" do
                プライバシーポリシー
            %li.description_list
              = link_to "#" do
                メルカリ利用規約
            %li.description_list
              = link_to "#" do
                あんしんスマホサポート制度に関する
            %li.description_list
              = link_to "#" do
                コンプライアンスポリシー
      .description1
        %div
          %ul
            %li.description_list
              = link_to "#" do
                個人データの安全管理に係る基本方針
            %li.description_list
              = link_to "#" do
                特定商取引に関する表記
            %li.description_list
              = link_to "#" do
                資金決済法に基づく表示
            %li.description_list
              = link_to "#" do
                法令遵守と犯罪抑制のために
      .description
        %h2 国
        %ul
          %li.description_list
            = link_to "#" do
              日本
          %li.description_list
            = link_to "#" do
              United States
    .footer_bottom
      = link_to "#" do
        =image_tag "logo_white.svg", id: "footer_icon", alt: ""
      %span.copy_right © FreeMarket Int.

app/views/items/_header.html.haml
%header
  #headerbg
    .header-top
      = link_to root_path do
        = image_tag "fmarket_logo_red.svg", id: "freemarket_string", alt: "freemarket"
      = form_with(url: search_items_path, local: true, method: :get) do |f|
        .search-field
          = f.text_field :keyword, placeholder: "何をお探しですか？", class:"search_form"
          %button.search_btn
            = f.submit class:"search-btn1"
            %i.fas.fa-search

        -# %div.search-field
        -#   %input.search_form{placeholder: "何をお探しですか？", type: "text"}/
        -#   %button.search_btn
        -#     = link_to "#" do
        -#       %i.fas.fa-search
    %nav.top_navi
      %ul.refarence
        %li.search_category
          %i.fas.fa-list-ul
          = link_to "#" do
            カテゴリーから探す
        %li.search_brand
          %i.fas.fa-tags
          = link_to "#" do
            ブランドから探す
      - if user_signed_in?
        %ul.top_lists
          %li.top_list
            %i.far.fa-heart
            = link_to "#" do
              いいね！一覧
          %li.top_list
            %i.far.fa-bell
            = link_to "#" do
              お知らせ
          %li.top_list
            %i.fas.fa-check
            = link_to "#" do
              やることリスト
          %li.top_list
            %i.fas.fa-user-circle
            = link_to user_path(current_user.id) do
              マイページ
      - else
        %ul.top_lists
          %li.top_list
            = link_to "新規登録", signup_index_path, class: "top-list-registration"
          %li.top_list
            = link_to "ログイン", new_user_session_path, class: "top-list-session"
    

app/views/items/_navs.html.haml
.nav
  %h2.popularity-category 人気のブランド
  .categories
    = link_to "#chanel" ,class:"women button" do
      シャネル
    = link_to "#louisvuitton" ,class:"men button" do
      ルイヴィトン
    = link_to "#supreme" ,class:"appliance button" do
      シュプリーム
    = link_to "#nike" ,class:"toy button" do
      ナイキ
.items-holders
  #chanel.item-title
    %h3.item-title-chanel シャネル新着アイテム
    = link_to "#" ,class:"see-more" do
      もっと見る
      %i.fas.fa-angle-right
  .holder
    .items-images
      %ul.images
        - @items.each do |item|
          %li.image
            .product
              = link_to item_path(item.id) ,class:"product-image" do
                .product-card
                  %span.product-price
                    ¥
                    = item.price.to_s(:delimited, delimiter: ',')
                  = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                  .product-description
                    %span
                      = item.name
        
  #louisvuitton.item-title
    %h3.item-title-louisvuitton ルイヴィトン新着アイテム
    = link_to "#" ,class:"see-more" do
      もっと見る
      %i.fas.fa-angle-right
  .holder
    .items-images
      %ul.images
        - @items.each do |item|
          %li.image
            .product
              = link_to item_path(item.id) ,class:"product-image" do
                .product-card
                  %span.product-price
                    ¥
                    = item.price.to_s(:delimited, delimiter: ',')
                  = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                  .product-description
                    %span
                      = item.name
        
  #supreme.item-title
    %h3.item-title-supreme シュプリーム新着アイテム
    = link_to "#" ,class:"see-more" do
      もっと見る
      %i.fas.fa-angle-right
  .holder
    .items-images
      %ul.images
        - @items.each do |item|
          %li.image
            .product
              = link_to item_path(item.id) ,class:"product-image" do
                .product-card
                  %span.product-price
                    ¥
                    = item.price.to_s(:delimited, delimiter: ',')
                  = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                  .product-description
                    %span
                      = item.name
       
  #nike.item-title
    %h3.item-title-nike ナイキ新着アイテム
    = link_to "#" ,class:"see-more" do
      もっと見る
      %i.fas.fa-angle-right
  .holder
    .items-images
      %ul.images
        - @items.each do |item|
          %li.image
            .product
              = link_to item_path(item.id) ,class:"product-image" do
                .product-card
                  %span.product-price
                    ¥
                    = item.price.to_s(:delimited, delimiter: ',')
                  = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                  .product-description
                    %span
                      = item.name
        

app/views/items/index.html.haml
= render "items/header"
-# - breadcrumb :root
-# = breadcrumbs pretext: "トップページ",separator: " &rsaquo; ", class: "breadcrumbs-list"
.main-top 
  .advertisements 
    .advertisement 
      %ul.advertisement-box
        %li
          = image_tag "pictweet.jpg", class: "scroll-advertisement one"
        %li
          = image_tag "sns_01.jpg", class: "scroll-advertisement second"
        %li
          = image_tag "pictweet.jpg", class: "scroll-advertisement third"
          .icon-icon-two
            = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8",class:"apple apple-one" do
              =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class:"apple"
            = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja",class: "google google-one" do
              =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg" ,class:"google"
  .nav
    %h2.popularity-category 人気のカテゴリー
    .categories
      = link_to "#women" ,class:"women button" do
        レディース
      = link_to "#men" ,class:"men button" do
        メンズ
      = link_to "#appliance" ,class:"appliance button" do
        家電・スマホ・カメラ
      = link_to "#toy" ,class:"toy button" do
        おもちゃ・ホビー・グッズ
  .items-holders
    #women.item-title
      %h3.item-title-women レディース新着アイテム
      = link_to "#" ,class:"see-more" do
        もっと見る
        %i.fas.fa-angle-right
    .holder
      .items-images
        %ul.images
          - @items.each do |item|
            %li.image
              .product
                = link_to item_path(item.id) ,class:"product-image" do
                  .product-card
                    %span.product-price
                      ¥
                      = item.price.to_s(:delimited, delimiter: ',')
                    = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                    .product-description
                      %span
                        = item.name

    #men.item-title
      %h3.item-title-men メンズ新着アイテム
      = link_to "#" ,class:"see-more" do
        もっと見る
        %i.fas.fa-angle-right
    .holder
      .items-images
        %ul.images
          - @items.each do |item|
            %li.image
              .product
                = link_to item_path(item.id) ,class:"product-image" do
                  .product-card
                    %span.product-price
                      ¥
                      = item.price.to_s(:delimited, delimiter: ',')
                    = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                    .product-description
                      %span
                        = item.name

    #appliance.item-title
      %h3.item-title-appliance 家電・スマホ・カメラ新着アイテム
      = link_to "#" ,class:"see-more" do
        もっと見る
        %i.fas.fa-angle-right
    .holder
      .items-images
        %ul.images
          - @items.each do |item|
            %li.image
              .product
                = link_to item_path(item.id) ,class:"product-image" do
                  .product-card
                    %span.product-price
                      ¥
                      = item.price.to_s(:delimited, delimiter: ',')
                    = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                    .product-description
                      %span
                        = item.name

    #toy.item-title
      %h3.item-title-toy おもちゃ・ホビー・グッズ新着アイテム
      = link_to "#" ,class:"see-more" do
        もっと見る
        %i.fas.fa-angle-right
    .holder
      .items-images
        %ul.images
          - @items.each do |item|
            %li.image
              .product
                = link_to item_path(item.id) ,class:"product-image" do
                  .product-card
                    %span.product-price
                      ¥
                      = item.price.to_s(:delimited, delimiter: ',')
                    = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                    .product-description
                      %span
                        = item.name
  
  = render partial: "navs"
= render "items/footer"

app/views/items/purchase.html.haml
= render "signup/sign_up_header"
%main.purchase
  %section.purchase-container
    %h2.purchase-container-title 購入内容の確認
    %section.purchase-content-item
      .item-box
        = image_tag "#{@item.image}", alt: "購入アイテムの写真", height: "80px", width: "80px", class: "item-image"
        .item-detail-text
          %p.item-detail-name 
            = @item.name
          %p.item-detail-price
            %span.item-price-figure
              ¥
              = @item.price.to_s(:delimited, delimiter: ',')
            %span.item-price-tax （税込）送料込み
    %section.purchase-content
      .purchase-content-box
        %form.item-detail-form{action: "#"}
          %ul.price-table
            %li.price-table-row
              .price-table-cell.text-price 支払い金額
              .price-table-cell.price-cell
                %span 
                  ¥
                  = @item.price.to_s(:delimited, delimiter: ',')

          %ul.buy-point
            %li.buy-point-cell
              .checkbox-default.use-point
                %i.fas.fa-square
                %label.point-text ポイントを使用(所持ポイント:P0)
          %section.purchase-content
            .purchase-content-inner
              %div
                %h3.l-left 支払い方法
                = link_to "変更する", "#" ,class:"l-right change"
              %p.user-info-text
                クレジットカード
                %br>/
                = "**** **** ****" + @credit_information.last4
                %br>/
                = "有効期限" 
                %span
                = @credit_information.exp_month.to_s
                = "/"
                = @credit_information.exp_year.to_s.slice(2,3)
              .user-card-logo
                = @credit_brand
          %section.purchase-content-shippings
            .purchase-content-shipping
              %div
                %h3.l-left 配送先
                = link_to "変更する", "#" , class:"l-right change-second"
            %address.user-info-text
              %p
                〒 
                = current_user.profile.zip_code
                %br>/
                = current_user.profile.prefecture
                %span
                = current_user.profile.city
                %span
                = current_user.profile.house_number
                %br>/
                = current_user.profile.last_name
                %span
                = current_user.profile.first_name
        .buy__centerbox__buyinfo__buybutton
          = form_tag(action: :pay, method: :post) do
            %button.btn{type:"submit",class:"buy__centerbox__buyinfo__buybutton__red"} 購入する
= render "signup/sign_up_footer"

app/views/items/search.html.haml
= render "items/header"

.main-top 
  .advertisements 
    .advertisement 
      %ul.advertisement-box
        %li
          = image_tag "pictweet.jpg", class: "scroll-advertisement one"
        %li
          = image_tag "sns_01.jpg", class: "scroll-advertisement second"
        %li
          = image_tag "pictweet.jpg", class: "scroll-advertisement third"
          .icon-icon-two
            = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8",class:"apple apple-one" do
              =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class:"apple"
            = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja",class: "google google-one" do
              =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg" ,class:"google"
  .nav
    %h2.popularity-category 検索に引っかかった商品
    .categories
      
  .items-holders
    #women.item-title
      %h3.item-title-women 
      = link_to "#" ,class:"see-more" do
        もっと見る
        %i.fas.fa-angle-right
    .holder
      .items-images
        %ul.images
          - @items.each do |item|
            %li.image
              .product
                = link_to item_path(item.id) ,class:"product-image" do
                  .product-card
                    %span.product-price
                      = "¥#{item.price}"
                    = image_tag "#{item.image}", class:"product-image-size", alt: "商品写真"
                    .product-description
                      %span
                        = item.description

= render "items/footer"

app/views/items/show.html.haml
= render "items/header"
.item-detail
  .item-detail-contents
    %h1.item-detail-name
      = @item.name
    .item-detail-main.clearfix
      .item-detail-photo
        = image_tag "#{@item.image}", alt: '商品紹介', class: 'photo-main'
        -# .item-detail-photo-sub
        -#   = image_tag "#{@item.image}", alt: '商品紹介', class: 'photo-sub'
        -#   = image_tag "#{@item.image}", alt: '商品紹介', class: 'photo-sub'
      %table.item-detail-table
        %tbody
          %tr
            %th 出品者
            %td
              = link_to "#{@item.user.nickname}", class: "item-detail-username"
              %div
                %span.item-detail-evaluation
                  = icon('fas', 'laugh', class: 'laugh')
                  10
                %span.item-detail-evaluation
                  = icon('fas', 'meh', class: 'meh')
                  10
                %span.item-detail-evaluation
                  = icon('fas', 'frown', class: 'frown')
                  10
          %tr
            %th カテゴリー
            %td
              = link_to "#{@item.category1}", class:"item-detail-category" 
              = link_to "#{@item.category2}", class:"item-detail-category" do
                = icon('fas', 'angle-right')
                = @item.category2
              = link_to "#{@item.category3}", class: "item-detail-category" do
                = icon('fas', 'angle-right')
                = @item.category3
          %tr
            %th ブランド
            %td
              - unless @item.brand.blank?
                = @item.brand
          %tr
            %th 商品のサイズ
            %td
              - unless @item.size.blank?
                = @item.size 
          %tr
            %th 商品の状態
            %td
              = @item.status
          %tr
            %th 配送料の負担
            %td
              = @item.derivery_fee
          %tr
            %th 配送の方法
            %td
              = @item.derivery_method
          %tr
            %th 配送元地域
            %td
              = link_to "#{@item.prefecture_id}" 
          %tr
            %th 発送日の目安
            %td
              = @item.derivery_estimated

    .item-detail-price-box
      %span.item-detail-price
        = "¥#{price}"
      %span.item-detail-tax （税込）
      %span.item-detail-postage 送料込み
    - if user_signed_in? && current_user.id == @item.user_id
      = link_to "編集", "/items/#{@item.id}/edit",method: :get, class:"item-buy-btn"
      = link_to "削除", "/items/#{@item.id}",method: :delete, class:"item-buy-btn"
    - elsif user_signed_in? && @item.buyer_id.present?
      = link_to "購入画面に進む", "#", class: "item-buy-btn"
    - elsif user_signed_in?
      = link_to "購入画面に進む", item_purchase_path(@item.id), class: "item-buy-btn"
    - else
      = link_to "購入画面に進む", new_user_session_path, class: "item-buy-btn", onClick: "window.alert('ログインして下さい')"
    .item-detail-description
      %p.item-detail-description__sentence
        = @item.description
    .item-detail-button.clearfix
      .item-detail-button-left
        %button.item-detail-button-left__like.item-button
          = icon('far', 'heart', class: 'heart')
          %span いいね!
          %span 0
        = link_to "#", class: "item-detail-button-left__report item-button" do
          = icon('far', 'flag')
          %span 不適切な商品の報告
      .item-detail-button-right
        = link_to '#' do
          = icon('fas', 'lock')
          あんしん・あんぜんへの取り組み
  .item-detail-message
    .message-comments
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = text_area_tag class: 'form-comment'
      = submit_tag 'コメントする', class: 'form-submit'
  %ul.item-links.clearfix
    %li.item-link-pre
      = link_to "#", class: "item-link" do
        = icon('fas', 'angle-left', class: 'angle')
        %span 前のページ
    %li.item-link-next
      = link_to "#", class: "item-link" do
        %span 次のページ
        = icon('fas', 'angle-right', class: 'angle')
  .social-media-links
    %ul.social-media-boxes
      %li.social-media-box.facebook
        = link_to '#', class: 'social-icon' do
          %i.fab.fa-facebook-square.fa-3x
      %li.social-media-box.twitter
        = link_to '#', class: 'social-icon' do
          %i.fab.fa-twitter-square.fa-3x
      %li.social-media-box.pinterest
        = link_to '#', class: 'social-icon' do
          %i.fab.fa-pinterest-square.fa-3x
  .item-image-box
    .user-item-box.clearfix
      %h2.item-box-head
        = link_to "#", class: 'item-box-head' do
          = @item.user.nickname
      - @items.each do |item|
        .item-box
          = link_to '#', class: 'item-box-link' do
            = image_tag "#{item.image}", alt: '商品説明', class: 'item-box-photo'
            .item-box-body
              %h3.item-box-name
                = item.name
              .item-box-price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')


      -# .item-box
      -#   = link_to '#', class: 'item-box-link' do
      -#     = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
      -#     .item-box-body
      -#       %h3.item-box-name LIDNM ハイストレッチスキニー
      -#       .item-box-price ¥3,500
      -# .item-box
      -#   = link_to '#', class: 'item-box-link' do
      -#     = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
      -#     .item-box-body
      -#       %h3.item-box-name LIDNM ハイストレッチスキニー
      -#       .item-box-price ¥3,500
      -# .item-box
      -#   = link_to '#', class: 'item-box-link' do
      -#     = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
      -#     .item-box-body
      -#       %h3.item-box-name LIDNM ハイストレッチスキニー
      -#       .item-box-price ¥3,500
    -# .brand-item-box.clearfix
    -#   %h2.item-box-head
    -#     = link_to "#", class: 'item-box-head' do
    -#       リドムのデニム/ジーンズ その他の出品
    -#   .item-box
    -#     = link_to '#', class: 'item-box-link' do
    -#       = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
    -#       .item-box-body
    -#         %h3.item-box-name LIDNM ハイストレッチスキニー
    -#         .item-box-price ¥3,500
    -#   .item-box
    -#     = link_to '#', class: 'item-box-link' do
    -#       = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
    -#       .item-box-body
    -#         %h3.item-box-name LIDNM ハイストレッチスキニー
    -#         .item-box-price ¥3,500
    -#   .item-box
    -#     = link_to '#', class: 'item-box-link' do
    -#       = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
    -#       .item-box-body
    -#         %h3.item-box-name LIDNM ハイストレッチスキニー
    -#         .item-box-price ¥3,500
    -#   .item-box
    -#     = link_to '#', class: 'item-box-link' do
    -#       = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
    -#       .item-box-body
    -#         %h3.item-box-name LIDNM ハイストレッチスキニー
    -#         .item-box-price ¥3,500
    -#   .item-box
    -#     = link_to '#', class: 'item-box-link' do
    -#       = image_tag '138475205.jpg', alt: '商品説明', class: 'item-box-photo'
    -#       .item-box-body
    -#         %h3.item-box-name LIDNM ハイストレッチスキニー
    -#         .item-box-price ¥3,500
= render "items/footer"            